version: '3.8'
services:
  couchbase:
    build: .
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11207:11207"
      - "11210:11210"
      - "11211:11211"
    environment:
      - CB_REST_USERNAME=admin
      - CB_REST_PASSWORD=password
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
 couchbase_data: 